### ISSUE TITLE
Observable demo does not work

### ISSUE THREAD

**Issue by domoritz** [omnisci/vega-transform-omnisci-core#1]
See https://observablehq.com/@domoritz/vega-with-omnisci-core-transform

@jheer any idea why the transform is not being called? https://vega.github.io/scalable-vega/ works fine.

**Comment by jheer** [comment]
Ugh. The breakdown is due to redundant imports of Vega. It looks like we're getting two different versions: one loaded by the OmniSci plugin and the other by embed.

To make the queries run, I can hack the prototype chain like so: `QueryCore.prototype.__proto__ = embed.vega.transforms.collect.prototype.__proto__;`

However, downstream rendering is still buggy because the tuples ingested by the query transform use a different `Symbol` for the tuple id. If I set an explicit data join key on the `rect` mark (e.g., `"key": "bin_start") then the join skips the symbol-keyed id and rendering is fixed.

We need a way to ensure that different Vega versions are not loaded side-by-side. There are parts of the system that could be made more robust to prototype chain issues, but that still wouldn't solve the issue of having _different_ Symbol instances used to set/get Vega tuple ids.

I don't have good insight into Observable's `require` implementation to diagnose why it is not caching / reusing the `require('vega')` calls that both libraries make. Maybe @mbostock has an idea?

**Comment by mbostock** [comment]
This is arguably a caching bug on jsDelivr’s side. These two URLs resolve differently:

https://cdn.jsdelivr.net/npm/vega@*/package.json (resolves to 5.3.1)
https://cdn.jsdelivr.net/npm/vega/package.json (resolves to 5.3.2)

The first one comes from vega-embed’s peer dependency on `vega@*`. The second one comes from vega-transform-omnisci-core, which does not declare a vega dependency in its package.json, but since it does require vega at runtime, it resolves to `vega` with no version range, which is equivalent to `vega@latest` (and slightly different than `vega@*`).

So, the first thing I would do is to declare the dependencies consistently, say by adding `vega@*` as a peer dependency here.

The second thing is that you can purge the jsDelivr cache after releasing new software by replacing “cdn” in the link above with “purge”. This way, even though they are loaded with different URLs, they will resolve to the same value and not be loaded twice.

And lastly, you can again workaround these issues using require.alias to force them to resolve to the same value:

```js
require.alias({vega: 'vega@*'})('vega-transform-omnisci-core@0.0.8')
```

Or better, to pin major versions so that it won’t break when a new release is available:

https://observablehq.com/compare/1c142edfbb839048...cc4f77bed1274eee

**Comment by jheer** [comment]
Thanks @mbostock! Both the `purge` and `require.alias` tricks were new to me!

**Comment by jheer** [comment]
FYI, I purge'd `vega@*` and the notebook is now working. But we should still declare our dependencies in a systematic fashion.

**Comment by domoritz** [comment]
Thank you for finding the issue. I declared the peer dependency and so I think it should work better now.
